import type { OrderSummary, Product } from '@/types/store'

export const heroSlides = [
  {
    title: 'Protección premium para el invierno patagónico',
    description: 'Capas, camperas y abrigo técnico para perros que salen a la nieve, el viento y la humedad de Bariloche.',
    image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1600&q=80',
  },
  {
    title: 'Minimalismo outdoor, pensado para clima real',
    description: 'Texturas limpias, siluetas funcionales y materiales listos para acompañar aventura, confort y protección.',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1600&q=80',
  },
  {
    title: 'Entrega en el día en Bariloche',
    description: 'Comprando antes de las 14 hs, entregamos gratis el mismo día dentro de Bariloche.',
    image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1600&q=80',
  },
]

export const products: Product[] = [
  {
    id: 'prod-storm-shell',
    slug: 'capa-termica-storm-shell',
    name: 'Capa térmica Storm Shell',
    animalType: 'DOG',
    salesCount: 214,
    category: 'Capas',
    price: 119900,
    compareAtPrice: 139900,
    mainImageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1400&q=80',
    shortDescription: 'Cobertura total para nieve, viento y humedad con silueta limpia y ajuste seguro.',
    description: 'Diseñada para proteger del frío, la nieve, el viento y la humedad. Una capa técnica con exterior impermeable, interior térmico y calce pensado para acompañar movimiento sin perder cobertura.',
    useTags: ['Frío', 'Nieve', 'Lluvia'],
    featureTags: ['Impermeable', 'Térmica', 'Cortaviento', 'Liviana', 'Lavable'],
    materials: ['Exterior impermeable', 'Interior térmico', 'Ajuste seguro', 'Cobertura total'],
    careInstructions: ['Lavado suave', 'Secado a la sombra', 'No planchar membrana'],
    colors: [
      { name: 'Negro', hex: '#101010' },
      { name: 'Verde militar', hex: '#495247' },
      { name: 'Azul marino', hex: '#1d2738' },
    ],
    sizes: [
      { label: 'S', chest: '48-54 cm', length: '32 cm' },
      { label: 'M', chest: '55-62 cm', length: '40 cm' },
      { label: 'L', chest: '63-72 cm', length: '48 cm' },
      { label: 'XL', chest: '73-82 cm', length: '56 cm' },
    ],
    variants: [
      { id: 'storm-negro-s', colorName: 'Negro', colorHex: '#0B0B0B', size: 'S', stock: 5, sku: 'storm-shell-negro-s' },
      { id: 'storm-negro-m', colorName: 'Negro', colorHex: '#0B0B0B', size: 'M', stock: 8, sku: 'storm-shell-negro-m' },
      { id: 'storm-negro-l', colorName: 'Negro', colorHex: '#0B0B0B', size: 'L', stock: 4, sku: 'storm-shell-negro-l' },
      { id: 'storm-verde-s', colorName: 'Verde militar', colorHex: '#4B5320', size: 'S', stock: 3, sku: 'storm-shell-verde-s' },
      { id: 'storm-verde-m', colorName: 'Verde militar', colorHex: '#4B5320', size: 'M', stock: 5, sku: 'storm-shell-verde-m' },
      { id: 'storm-verde-l', colorName: 'Verde militar', colorHex: '#4B5320', size: 'L', stock: 2, sku: 'storm-shell-verde-l' },
      { id: 'storm-azul-m', colorName: 'Azul marino', colorHex: '#1C2A44', size: 'M', stock: 4, sku: 'storm-shell-azul-m' },
      { id: 'storm-azul-l', colorName: 'Azul marino', colorHex: '#1C2A44', size: 'L', stock: 6, sku: 'storm-shell-azul-l' },
      { id: 'storm-azul-xl', colorName: 'Azul marino', colorHex: '#1C2A44', size: 'XL', stock: 3, sku: 'storm-shell-azul-xl' },
    ],
    images: [
      {
        type: 'COLOR',
        colorName: 'Negro',
        url: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1400&q=80',
        alt: 'Perro usando capa térmica negra en nieve',
        sortOrder: 0,
      },
      {
        type: 'COLOR',
        colorName: 'Verde militar',
        url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1400&q=80',
        alt: 'Perro usando capa térmica verde militar',
        sortOrder: 1,
      },
      {
        type: 'COLOR',
        colorName: 'Azul marino',
        url: 'https://images.unsplash.com/photo-1525253086316-d0c936c814f8?auto=format&fit=crop&w=1400&q=80',
        alt: 'Perro usando capa térmica azul marino',
        sortOrder: 2,
      },
      {
        type: 'INFO',
        url: 'https://images.unsplash.com/photo-1518715308788-3005759c95e8?auto=format&fit=crop&w=1400&q=80',
        alt: 'Detalle de materiales y terminaciones',
        sortOrder: 10,
      },
    ],
    reviews: [],
  },
  {
    id: 'prod-ridge-park',
    slug: 'campera-ridge-park',
    name: 'Campera Ridge Park',
    animalType: 'DOG',
    salesCount: 186,
    category: 'Camperas',
    price: 128500,
    mainImageUrl: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1400&q=80',
    shortDescription: 'Relleno térmico liviano y cuello alto para salidas urbanas y montaña.',
    description: 'Una campera editorial y funcional para perros activos en clima frío. Conserva temperatura, corta viento y acompaña caminatas largas sin volumen excesivo.',
    useTags: ['Frío', 'Viento'],
    featureTags: ['Térmica', 'Cortaviento', 'Cómoda'],
    materials: ['Exterior técnico', 'Interior térmico', 'Cierre rápido', 'Cuello alto'],
    careInstructions: ['Lavado a mano', 'No centrifugar'],
    colors: [
      { name: 'Negro', hex: '#101010' },
      { name: 'Grafito', hex: '#484848' },
    ],
    sizes: [
      { label: 'M', chest: '54-62 cm', length: '38 cm' },
      { label: 'L', chest: '63-70 cm', length: '46 cm' },
      { label: 'XL', chest: '71-80 cm', length: '54 cm' },
    ],
    variants: [
      { id: 'ridge-negro-m', colorName: 'Negro', colorHex: '#0B0B0B', size: 'M', stock: 6, sku: 'ridge-park-negro-m' },
      { id: 'ridge-negro-l', colorName: 'Negro', colorHex: '#0B0B0B', size: 'L', stock: 5, sku: 'ridge-park-negro-l' },
      { id: 'ridge-negro-xl', colorName: 'Negro', colorHex: '#0B0B0B', size: 'XL', stock: 2, sku: 'ridge-park-negro-xl' },
      { id: 'ridge-grafito-m', colorName: 'Grafito', colorHex: '#484848', size: 'M', stock: 3, sku: 'ridge-park-grafito-m' },
      { id: 'ridge-grafito-l', colorName: 'Grafito', colorHex: '#484848', size: 'L', stock: 4, sku: 'ridge-park-grafito-l' },
      { id: 'ridge-grafito-xl', colorName: 'Grafito', colorHex: '#484848', size: 'XL', stock: 4, sku: 'ridge-park-grafito-xl' },
    ],
    images: [
      {
        type: 'COLOR',
        colorName: 'Negro',
        url: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1400&q=80',
        alt: 'Perro con campera negra en exterior',
        sortOrder: 0,
      },
      {
        type: 'COLOR',
        colorName: 'Grafito',
        url: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=1400&q=80',
        alt: 'Perro con campera grafito',
        sortOrder: 1,
      },
      {
        type: 'LIFESTYLE',
        url: 'https://images.unsplash.com/photo-1444212477490-ca407925329e?auto=format&fit=crop&w=1400&q=80',
        alt: 'Lifestyle de campera en salida de invierno',
        sortOrder: 10,
      },
    ],
    reviews: [],
  },
  {
    id: 'prod-snow-rest',
    slug: 'manta-snow-rest',
    name: 'Manta Snow Rest',
    animalType: 'DOG',
    salesCount: 97,
    category: 'Mantas',
    price: 54900,
    mainImageUrl: 'https://images.unsplash.com/photo-1548681528-6a5c45b66b42?auto=format&fit=crop&w=1400&q=80',
    shortDescription: 'Abrigo liviano para descanso, auto y refugio indoor con tacto premium.',
    description: 'Una manta de textura sobria y térmica para acompañar descanso después de la aventura o sumar calor sobre cama y transportadora.',
    useTags: ['Frío', 'Hogar'],
    featureTags: ['Térmica', 'Liviana'],
    materials: ['Microfibra térmica', 'Textura doble cara'],
    careInstructions: ['Lavar con agua fría'],
    colors: [
      { name: 'Negro', hex: '#111111' },
      { name: 'Piedra', hex: '#b1b0ac' },
    ],
    sizes: [
      { label: 'Único', chest: '-', length: '95 x 75 cm' },
    ],
    variants: [
      { id: 'snow-rest-negro', colorName: 'Negro', colorHex: '#111111', size: 'Único', stock: 10, sku: 'snow-rest-negro' },
      { id: 'snow-rest-piedra', colorName: 'Piedra', colorHex: '#B1B0AC', size: 'Único', stock: 7, sku: 'snow-rest-piedra' },
    ],
    images: [
      {
        type: 'COLOR',
        colorName: 'Negro',
        url: 'https://images.unsplash.com/photo-1548681528-6a5c45b66b42?auto=format&fit=crop&w=1400&q=80',
        alt: 'Manta premium para perro en interior',
        sortOrder: 0,
      },
      {
        type: 'COLOR',
        colorName: 'Piedra',
        url: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=1400&q=80',
        alt: 'Manta color piedra para perro',
        sortOrder: 1,
      },
    ],
    reviews: [],
  },
  {
    id: 'prod-arctic-collar',
    slug: 'accesorio-arctic-collar',
    name: 'Accesorio Arctic Collar',
    animalType: 'DOG',
    salesCount: 132,
    category: 'Accesorios',
    price: 32900,
    mainImageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1400&q=80',
    shortDescription: 'Cuello técnico para sumar abrigo en ráfagas, nieve húmeda y amaneceres helados.',
    description: 'Una pieza técnica compacta que aporta abrigo puntual en zona de cuello y pecho, ideal para capas por debajo de la campera.',
    useTags: ['Frío', 'Viento'],
    featureTags: ['Liviana', 'Térmica'],
    materials: ['Neopreno suave', 'Interior térmico'],
    careInstructions: ['Lavado delicado'],
    colors: [
      { name: 'Negro', hex: '#101010' },
      { name: 'Azul marino', hex: '#1d2738' },
    ],
    sizes: [
      { label: 'S', chest: '44-50 cm', length: '18 cm' },
      { label: 'M', chest: '51-60 cm', length: '22 cm' },
    ],
    variants: [
      { id: 'arctic-negro-s', colorName: 'Negro', colorHex: '#0B0B0B', size: 'S', stock: 8, sku: 'arctic-negro-s' },
      { id: 'arctic-negro-m', colorName: 'Negro', colorHex: '#0B0B0B', size: 'M', stock: 5, sku: 'arctic-negro-m' },
      { id: 'arctic-azul-s', colorName: 'Azul marino', colorHex: '#1C2A44', size: 'S', stock: 4, sku: 'arctic-azul-s' },
      { id: 'arctic-azul-m', colorName: 'Azul marino', colorHex: '#1C2A44', size: 'M', stock: 6, sku: 'arctic-azul-m' },
    ],
    images: [
      {
        type: 'COLOR',
        colorName: 'Negro',
        url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1400&q=80',
        alt: 'Accesorio de cuello negro',
        sortOrder: 0,
      },
      {
        type: 'COLOR',
        colorName: 'Azul marino',
        url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1400&q=80',
        alt: 'Accesorio de cuello azul marino',
        sortOrder: 1,
      },
    ],
    reviews: [],
  },
  {
    id: 'prod-feline-puffer',
    slug: 'parka-feline-puffer',
    name: 'Parka Feline Puffer',
    animalType: 'CAT',
    salesCount: 64,
    category: 'Parkas',
    price: 98700,
    mainImageUrl: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=1400&q=80',
    shortDescription: 'Parka térmica liviana para gatos de interior con balcón, patio y traslados en clima frío.',
    description: 'Una parka premium pensada para gatos sensibles al frío. Prioriza abrigo liviano, suavidad interior y un acceso cómodo para colocación rápida sin perder cobertura.',
    useTags: ['Frío', 'Interior', 'Traslado'],
    featureTags: ['Térmica', 'Liviana', 'Cómoda'],
    materials: ['Exterior softshell', 'Interior térmico', 'Ajuste suave', 'Cobertura dorsal'],
    careInstructions: ['Lavado delicado', 'Secado plano'],
    colors: [
      { name: 'Negro', hex: '#111111' },
      { name: 'Piedra', hex: '#C8C2B8' },
    ],
    sizes: [
      { label: '1', chest: '30-34 cm', length: '24 cm' },
      { label: '2', chest: '35-39 cm', length: '28 cm' },
      { label: '3', chest: '40-44 cm', length: '32 cm' },
    ],
    variants: [
      { id: 'feline-negro-1', colorName: 'Negro', colorHex: '#111111', size: '1', stock: 4, sku: 'feline-puffer-negro-1' },
      { id: 'feline-negro-2', colorName: 'Negro', colorHex: '#111111', size: '2', stock: 5, sku: 'feline-puffer-negro-2' },
      { id: 'feline-piedra-2', colorName: 'Piedra', colorHex: '#C8C2B8', size: '2', stock: 3, sku: 'feline-puffer-piedra-2' },
      { id: 'feline-piedra-3', colorName: 'Piedra', colorHex: '#C8C2B8', size: '3', stock: 2, sku: 'feline-puffer-piedra-3' },
    ],
    images: [
      {
        type: 'COLOR',
        colorName: 'Negro',
        url: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=1400&q=80',
        alt: 'Gato con parka negra premium',
        sortOrder: 0,
      },
      {
        type: 'COLOR',
        colorName: 'Piedra',
        url: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=1400&q=80',
        alt: 'Gato con parka color piedra',
        sortOrder: 1,
      },
    ],
    reviews: [],
  },
  {
    id: 'prod-feline-knit',
    slug: 'buzo-feline-knit',
    name: 'Buzo Feline Knit',
    animalType: 'CAT',
    salesCount: 51,
    category: 'Buzos',
    price: 62400,
    mainImageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1400&q=80',
    shortDescription: 'Buzo térmico suave para gatos friolentos con calce flexible y perfil minimal.',
    description: 'Buzo premium para uso indoor e intermedio. Diseñado para sumar calor sin rigidez, ideal para gatos seniors, de pelo corto o en recuperación.',
    useTags: ['Frío', 'Interior'],
    featureTags: ['Térmica', 'Lavable', 'Liviana'],
    materials: ['Tejido térmico', 'Interior suave', 'Costuras planas'],
    careInstructions: ['Lavado suave', 'No secadora'],
    colors: [
      { name: 'Grafito', hex: '#444444' },
      { name: 'Verde bosque', hex: '#334538' },
    ],
    sizes: [
      { label: '1', chest: '29-33 cm', length: '22 cm' },
      { label: '2', chest: '34-38 cm', length: '26 cm' },
    ],
    variants: [
      { id: 'feline-knit-grafito-1', colorName: 'Grafito', colorHex: '#444444', size: '1', stock: 6, sku: 'feline-knit-grafito-1' },
      { id: 'feline-knit-grafito-2', colorName: 'Grafito', colorHex: '#444444', size: '2', stock: 4, sku: 'feline-knit-grafito-2' },
      { id: 'feline-knit-bosque-1', colorName: 'Verde bosque', colorHex: '#334538', size: '1', stock: 3, sku: 'feline-knit-bosque-1' },
      { id: 'feline-knit-bosque-2', colorName: 'Verde bosque', colorHex: '#334538', size: '2', stock: 2, sku: 'feline-knit-bosque-2' },
    ],
    images: [
      {
        type: 'COLOR',
        colorName: 'Grafito',
        url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1400&q=80',
        alt: 'Gato con buzo grafito',
        sortOrder: 0,
      },
      {
        type: 'COLOR',
        colorName: 'Verde bosque',
        url: 'https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=1400&q=80',
        alt: 'Gato con buzo verde bosque',
        sortOrder: 1,
      },
    ],
    reviews: [],
  },
]

export const faqItems = [
  {
    question: '¿Por qué abrigar al perro en Bariloche?',
    answer: 'El viento, la nieve y la humedad bajan la temperatura corporal con rapidez, sobre todo en perros de pelo corto, cachorros, seniors y razas pequeñas.',
  },
  {
    question: '¿La entrega en el día aplica siempre?',
    answer: 'Sí dentro de Bariloche, comprando antes de las 14 hs y sujeto a disponibilidad de stock.',
  },
  {
    question: '¿Hacen envíos nacionales?',
    answer: 'Sí. La tienda queda preparada para envíos a todo el país y checkout con estado pendiente de pago.',
  },
]

export const sampleOrders: OrderSummary[] = [
  {
    id: 'PA-24051',
    status: 'preparando',
    createdAt: '2026-05-03',
    total: 119900,
    shipping: 'Bariloche entrega gratis en el día',
    items: [{ name: 'Capa térmica Storm Shell', quantity: 1, color: 'Negro', size: 'L' }],
  },
  {
    id: 'PA-24048',
    status: 'entregado',
    createdAt: '2026-04-28',
    total: 183400,
    shipping: 'Envío nacional',
    items: [
      { name: 'Campera Ridge Park', quantity: 1, color: 'Grafito', size: 'XL' },
      { name: 'Manta Snow Rest', quantity: 1, color: 'Piedra', size: 'Único' },
    ],
  },
]
